---
name: Catalyst-View-XSLT
version: 0.04
author: []
abstract: XSLT View Class
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Catalyst: 5.7
  Data::Dumper: 2
  File::Spec: 3.1
  Path::Class: 0.12
  UNIVERSAL::require: 0.1
  XML::LibXSLT: 1.52
build_requires:
  FindBin: 1.4
  Test::More: 0.6
provides:
  Catalyst::Helper::View::XSLT:
    file: lib/Catalyst/Helper/View/XSLT.pm
    version: 0.04
  Catalyst::View::XSLT:
    file: lib/Catalyst/View/XSLT.pm
    version: 0.04
  Catalyst::View::XSLT::XML::LibXSLT:
    file: lib/Catalyst/View/XSLT/XML/LibXSLT.pm
    version: 0.04
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
