---
name: Catalyst-View-XSLT
version: 0.08
author:
  - 'Simon Bertrang, E<lt>simon.bertrang@puzzworks.comE<gt>'
abstract: XSLT View Class
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Catalyst: 5.7
  Data::Dumper: 2
  File::Spec: 3.1
  Path::Class: 0.12
  XML::LibXSLT: 1.52
build_requires:
  FindBin: 1.4
  Test::More: 0.6
provides:
  Catalyst::Helper::View::XSLT:
    file: lib/Catalyst/Helper/View/XSLT.pm
    version: 0.08
  Catalyst::View::XSLT:
    file: lib/Catalyst/View/XSLT.pm
    version: 0.08
  Catalyst::View::XSLT::XML::LibXSLT:
    file: lib/Catalyst/View/XSLT/XML/LibXSLT.pm
    version: 0.08
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
